### ISSUE TITLE
please add a mocked example

### ISSUE THREAD

**Issue by MushiTheMoshi** [aws/aws-lambda-go#534]
Hi there,

Nice work done here! Appreciated!

Wondering if you could include an example using mock as some times and for some of the services throttling is an issue...

Regards,
Julio

**Comment by MushiTheMoshi** [comment]
sorry, looks like I need to checked my eyes xD

**Comment by bmoffatt** [comment]
I think you're looking general AWS SDK documentation, rather than something specific to using Go in AWS Lambda. This repo is focused solely on the integration with the AWS Lambda execution environment.

https://aws.github.io/aws-sdk-go-v2/docs/unit-testing/#mocking-client-operations might be what you're looking for.
